on:
    push:
      branches:
        - main
        - master
        - release*
        - develop
jobs:
  example_matrix:
    strategy:
      matrix:
        fruit: [apple, pear]
        animal: [cat, dog]
        include:
          - color: green
          - color: pink
            animal: cat
          - fruit: apple
            shape: circle
          - fruit: banana
          - fruit: banana
            animal: cat
    runs-on: ubuntu
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

